#!/usr/bin/env python3
"""
Vivado Assistant Automation CLI.

This tool is intentionally script-first: it discovers a Vivado project, exports
version-sensitive assets with the source Vivado version, then rebuilds a clean
project in the target Vivado version from user-owned sources and exported BD Tcl.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable
from xml.etree import ElementTree


CONFIG_FILE_NAME = "vivado_assistant_config.json"
HDL_EXTS = {".v", ".sv", ".vhd", ".vhdl"}
XDC_EXTS = {".xdc"}
APP_EXTS = {".c", ".cc", ".cpp", ".h", ".hpp", ".ld", ".s", ".S"}
IGNORE_DIRS = {
    ".git",
    ".Xil",
    ".cache",
    ".gen",
    ".hw",
    ".ip_user_files",
    ".runs",
    ".sim",
    "xsim.dir",
    "ipcache",
}


@dataclass
class ProjectManifest:
    source_project: str
    project_name: str
    part: str
    board_part: str
    target_language: str
    simulator_language: str
    top: str
    hdl_files: list[str]
    xdc_files: list[str]
    app_files: list[str]
    bd_files: list[str]
    xci_files: list[str]


MAKEFILE_2021_1_FIX = """# Makefile generated by Xilinx.

DRIVER_LIB_VERSION = 1.0
PROCESSOR = ps7_cortexa9_0
LIBRARIES = ${PROCESSOR}/lib/libxil.a
BSP_MAKEFILES := $(wildcard $(PROCESSOR)/libsrc/*/src/Makefile)
SUBDIRS := $(patsubst %/Makefile, %, $(BSP_MAKEFILES))
BSP_SEQUENTIAL_MAKEFILES := __SEQUENTIAL_MAKEFILES__
BSP_PARALLEL_MAKEFILES := $(filter-out $(BSP_SEQUENTIAL_MAKEFILES),$(BSP_MAKEFILES))
SEQ_SUBDIRS := $(patsubst %/Makefile, %, $(BSP_SEQUENTIAL_MAKEFILES))
PAR_SUBDIRS := $(patsubst %/Makefile, %, $(BSP_PARALLEL_MAKEFILES))

ifneq (,$(findstring win,$(RDI_PLATFORM)))
 SHELL = CMD
endif

all:
\t$(MAKE) --no-print-directory seq_libs
\t$(MAKE) -j __JOBS__ --no-print-directory par_libs
\t$(MAKE) --no-print-directory archive
\t@echo 'Finished building libraries'

include: $(addsuffix /make.include,$(SUBDIRS))

seq_libs: $(addsuffix /make.libs,$(SEQ_SUBDIRS))
\t@echo 'Finished building libraries sequentially.'

par_libs: $(addsuffix /make.libs,$(PAR_SUBDIRS))
\t@echo 'Finished building libraries parallelly.'

archive:
\tarm-none-eabi-ar -r  $(LIBRARIES) $(wildcard $(PROCESSOR)/lib/*.o)

clean: $(addsuffix /make.clean,$(SUBDIRS))
\trm -f ${PROCESSOR}/lib/libxil.a

$(PROCESSOR)/lib/libxil.a: $(PROCESSOR)/lib/libxil_init.a
\tcp -f $< $@

%/make.include: $(if $(wildcard $(PROCESSOR)/lib/libxil_init.a),$(PROCESSOR)/lib/libxil.a,)
\t@echo "Running Make include in $(subst /make.include,,$@)"
\t$(MAKE) -C $(subst /make.include,,$@) -s include  "SHELL=$(SHELL)" "COMPILER=arm-none-eabi-gcc" "ASSEMBLER=arm-none-eabi-as" "ARCHIVER=arm-none-eabi-ar" "COMPILER_FLAGS=  -O2 -c" "EXTRA_COMPILER_FLAGS=-mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -nostartfiles -g -Wall -Wextra -fno-tree-loop-distribute-patterns"

%/make.libs: include
\t@echo "Running Make libs in $(subst /make.libs,,$@)"
\t$(MAKE) -C $(subst /make.libs,,$@) -s libs  "SHELL=$(SHELL)" "COMPILER=arm-none-eabi-gcc" "ASSEMBLER=arm-none-eabi-as" "ARCHIVER=arm-none-eabi-ar" "COMPILER_FLAGS=  -O2 -c" "EXTRA_COMPILER_FLAGS=-mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -nostartfiles -g -Wall -Wextra -fno-tree-loop-distribute-patterns"

%/make.clean:
\t$(MAKE) -C $(subst /make.clean,,$@) -s clean
"""


def norm(path: Path) -> str:
    return path.resolve().as_posix()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def default_config_path() -> Path:
    return Path.cwd() / CONFIG_FILE_NAME


def load_config(path: str | None = None) -> dict[str, str]:
    config_path = Path(path).resolve() if path else default_config_path()
    if not config_path.exists():
        return {}
    return json.loads(config_path.read_text(encoding="utf-8-sig"))


def save_config(config: dict[str, str], path: str | None = None) -> Path:
    config_path = Path(path).resolve() if path else default_config_path()
    ensure_dir(config_path.parent)
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
    return config_path


def version_key(version: str) -> str:
    return "vivado_" + version.replace(".", "_")


def looks_like_windows_path(value: str) -> bool:
    return len(value) >= 3 and value[1:3] in {":\\", ":/"}


def resolve_vivado_launcher(raw: str) -> tuple[str, list[str]]:
    """Resolve common Vivado path inputs to bin/vivado.bat or vivado executable.

    Users and agents often paste a Start Menu folder, an unwrapped/win64.o
    directory, or the executable itself. This function keeps path choice
    deterministic and prevents agents from running Tcl in the wrong folder.
    """
    notes: list[str] = []
    if not raw:
        return "", ["empty path"]

    expanded = os.path.expandvars(str(raw).strip().strip('"'))
    p = Path(expanded)
    candidates: list[Path] = []

    if p.is_file():
        candidates.append(p)
    if p.is_dir():
        candidates.extend(
            [
                p / "vivado.bat",
                p / "vivado.exe",
                p / "bin" / "vivado.bat",
                p / "bin" / "vivado.exe",
            ]
        )
        for parent in [p, *p.parents]:
            candidates.extend([parent / "bin" / "vivado.bat", parent / "bin" / "vivado.exe"])
            if parent.name.lower() == "bin":
                candidates.extend([parent / "vivado.bat", parent / "vivado.exe"])

    seen: set[str] = set()
    def candidate_rank(path: Path) -> tuple[int, int]:
        text = str(path).lower().replace("/", "\\")
        is_bat = 0 if path.name.lower() == "vivado.bat" else 1
        is_wrapped_bin = 0 if "\\bin\\vivado.bat" in text and "\\unwrapped\\" not in text else 1
        return (is_bat, is_wrapped_bin)

    for candidate in sorted(candidates, key=candidate_rank):
        key = str(candidate).lower()
        if key in seen:
            continue
        seen.add(key)
        if candidate.exists() and candidate.name.lower() in {"vivado.bat", "vivado.exe", "vivado"}:
            return str(candidate.resolve()), notes

    if p.exists():
        notes.append(f"path exists but no Vivado launcher was found under it: {p}")
    else:
        notes.append(f"path does not exist from this shell: {p}")
    notes.append("expected a Vivado install launcher such as <Vivado>/<version>/bin/vivado.bat")
    return str(p), notes


def require_host_can_run(vivado: str) -> None:
    if platform.system().lower() != "windows" and looks_like_windows_path(vivado):
        raise SystemExit(
            "This shell is not Windows, but the Vivado path is a Windows path. "
            "Run this command from the Windows environment that owns Vivado so "
            "the automation can execute Vivado and inspect logs directly."
        )


def workflow_path(root: Path, value: str) -> Path:
    path = Path(value)
    return path.resolve() if path.is_absolute() else (root / path).resolve()


def configured_vivados(config: dict[str, str]) -> dict[str, str]:
    return {key: value for key, value in config.items() if key.startswith("vivado_") and value}


def sole_configured_vivado(config: dict[str, str]) -> str:
    entries = configured_vivados(config)
    if len(entries) == 1:
        return next(iter(entries.values()))
    return ""


def resolve_vivado(args: argparse.Namespace, preferred: str = "") -> str:
    explicit = getattr(args, "vivado", "")
    if explicit:
        return explicit
    config = load_config(getattr(args, "assistant_config", None))
    default_version = config.get("default_vivado_version", "")
    default_key = version_key(default_version) if default_version else ""
    selected = (
        (config.get(version_key(preferred)) if preferred else "")
        or (config.get(preferred) if preferred else "")
        or config.get(default_key, "")
        or config.get("default_vivado", "")
        or sole_configured_vivado(config)
        or config.get("vivado", "")
        or "vivado"
    )
    resolved, notes = resolve_vivado_launcher(selected)
    if notes and selected != "vivado":
        print("WARNING: could not normalize Vivado path:")
        for note in notes:
            print(f"  - {note}")
    return resolved


def resolve_versioned_vivado(
    config: dict[str, str],
    explicit_path: str,
    explicit_version: str,
    role: str,
    fallback: str = "",
) -> str:
    if explicit_path:
        resolved, notes = resolve_vivado_launcher(explicit_path)
        if notes:
            raise SystemExit(f"Invalid {role} Vivado path:\n  - " + "\n  - ".join(notes))
        return resolved
    if explicit_version:
        key = version_key(explicit_version)
        value = config.get(key, "")
        if not value:
            raise SystemExit(
                f"{role} version {explicit_version} was requested, but {key} is not configured. "
                f"Run init first or pass --{role}-vivado explicitly."
            )
        resolved, notes = resolve_vivado_launcher(value)
        if notes:
            raise SystemExit(f"Invalid configured {role} Vivado path:\n  - " + "\n  - ".join(notes))
        return resolved
    if fallback:
        return fallback
    raise SystemExit(f"No {role} Vivado was specified.")


def init_config_cmd(args: argparse.Namespace) -> int:
    if not args.vivado_2020_2 and not args.vivado_2021_1:
        raise SystemExit("Provide at least one Vivado path, for example --vivado-2021-1 <path>.")

    config = load_config(args.assistant_config)
    if args.vivado_2020_2:
        path, notes = resolve_vivado_launcher(args.vivado_2020_2)
        if notes:
            raise SystemExit("Invalid Vivado 2020.2 path:\n  - " + "\n  - ".join(notes))
        config["vivado_2020_2"] = path
    if args.vivado_2021_1:
        path, notes = resolve_vivado_launcher(args.vivado_2021_1)
        if notes:
            raise SystemExit("Invalid Vivado 2021.1 path:\n  - " + "\n  - ".join(notes))
        config["vivado_2021_1"] = path

    default_version = args.default_version
    if default_version == "auto":
        if args.vivado_2021_1 or config.get("vivado_2021_1"):
            default_version = "2021.1"
        elif args.vivado_2020_2 or config.get("vivado_2020_2"):
            default_version = "2020.2"
        else:
            default_version = ""
    if default_version:
        default_path = config.get(version_key(default_version), "")
        if not default_path:
            raise SystemExit(f"Default version {default_version} has no configured path.")
        config["default_vivado_version"] = default_version
        config["default_vivado"] = default_path

    config_path = save_config(config, args.assistant_config)
    print(f"Wrote config: {config_path}")
    print(f"Vivado 2020.2: {config.get('vivado_2020_2', '')}")
    print(f"Vivado 2021.1: {config.get('vivado_2021_1', '')}")
    print(f"Default Vivado: {config.get('default_vivado_version', '')} {config.get('default_vivado', '')}")
    return 0


def register_board_xdc_cmd(args: argparse.Namespace) -> int:
    config = load_config(args.assistant_config)
    boards = config.setdefault("boards", {})
    board = boards.setdefault(args.board_name, {})
    board["xdc"] = str(Path(args.xdc).resolve())
    if args.part:
        board["part"] = args.part
    if args.board_part:
        board["board_part"] = args.board_part
    if args.description:
        board["description"] = args.description
    config_path = save_config(config, args.assistant_config)
    print(f"Wrote config: {config_path}")
    print(f"Board {args.board_name}: {board['xdc']}")
    if board.get("board_part"):
        print(f"  board_part: {board['board_part']}")
    return 0


def list_board_xdc_cmd(args: argparse.Namespace) -> int:
    config = load_config(args.assistant_config)
    boards = config.get("boards", {})
    if not boards:
        print("No board XDC files registered.")
        return 0
    for name, data in sorted(boards.items()):
        print(f"{name}: {data.get('xdc', '')}")
        if data.get("part"):
            print(f"  part: {data['part']}")
        if data.get("board_part"):
            print(f"  board_part: {data['board_part']}")
        if data.get("description"):
            print(f"  description: {data['description']}")
    return 0


def resolve_board_xdc(args: argparse.Namespace) -> str:
    if not getattr(args, "board_name", ""):
        return ""
    config = load_config(getattr(args, "assistant_config", None))
    board = config.get("boards", {}).get(args.board_name, {})
    return board.get("xdc", "")


def resolve_board_part(args: argparse.Namespace) -> str:
    explicit = getattr(args, "board_part", "")
    if explicit:
        return explicit
    if not getattr(args, "board_name", ""):
        return ""
    config = load_config(getattr(args, "assistant_config", None))
    board = config.get("boards", {}).get(args.board_name, {})
    return board.get("board_part", "")


def find_xpr(project: Path) -> Path:
    if project.is_file() and project.suffix.lower() == ".xpr":
        return project.resolve()
    matches = sorted(project.rglob("*.xpr"))
    if not matches:
        raise FileNotFoundError(f"No .xpr file found under {project}")
    if len(matches) > 1:
        preferred = [p for p in matches if ".runs" not in p.parts and ".cache" not in p.parts]
        matches = preferred or matches
    return matches[0].resolve()


def find_standard_impl_bit(project: Path) -> Path:
    xpr = find_xpr(project)
    impl_dir = xpr.parent / f"{xpr.stem}.runs" / "impl_1"
    bits = sorted(impl_dir.glob("*.bit"))
    if not bits:
        raise FileNotFoundError(f"No standard implementation bitstream found under {impl_dir}")
    return bits[0].resolve()


def parse_xpr_basic(xpr: Path) -> dict[str, str]:
    data = {
        "project_name": xpr.stem,
        "part": "xc7z020clg400-1",
        "board_part": "",
        "target_language": "Verilog",
        "simulator_language": "Mixed",
        "top": "",
    }
    try:
        root = ElementTree.parse(xpr).getroot()
    except ElementTree.ParseError:
        return data

    text = ElementTree.tostring(root, encoding="unicode")
    for key in ("Part", "PART", "part"):
        marker = f'Name="{key}" Val="'
        if marker in text:
            data["part"] = text.split(marker, 1)[1].split('"', 1)[0]
            break
    for key in ("BoardPart", "board_part"):
        marker = f'Name="{key}" Val="'
        if marker in text:
            data["board_part"] = text.split(marker, 1)[1].split('"', 1)[0]
            break
    for key, out_key in (
        ("TargetLanguage", "target_language"),
        ("SimulatorLanguage", "simulator_language"),
        ("TopModule", "top"),
    ):
        marker = f'Name="{key}" Val="'
        if marker in text:
            data[out_key] = text.split(marker, 1)[1].split('"', 1)[0]
    return data


def should_ignore(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.parts)


def collect_files(root: Path, exts: set[str]) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*"):
        if should_ignore(path):
            continue
        if path.is_file() and path.suffix in exts:
            files.append(path.resolve())
    return sorted(files)


def manifest_from_project(project: Path) -> ProjectManifest:
    xpr = find_xpr(project)
    root = xpr.parent
    info = parse_xpr_basic(xpr)
    bd_files = collect_files(root, {".bd"})
    xci_files = collect_files(root, {".xci"})
    hdl_files = collect_files(root, HDL_EXTS)
    xdc_files = collect_files(root, XDC_EXTS)
    app_files = collect_files(root, APP_EXTS)
    return ProjectManifest(
        source_project=norm(xpr),
        project_name=info["project_name"],
        part=info["part"],
        board_part=info["board_part"],
        target_language=info["target_language"],
        simulator_language=info["simulator_language"],
        top=info["top"],
        hdl_files=[norm(p) for p in hdl_files],
        xdc_files=[norm(p) for p in xdc_files],
        app_files=[norm(p) for p in app_files],
        bd_files=[norm(p) for p in bd_files],
        xci_files=[norm(p) for p in xci_files],
    )


def tcl_list(paths: Iterable[str]) -> str:
    return " ".join("{" + p.replace("\\", "/") + "}" for p in paths)


def write_export_tcl(manifest: ProjectManifest, out_dir: Path) -> Path:
    script = out_dir / "01_export_bd_from_source_vivado.tcl"
    bd_out = (out_dir / "bd_tcl").resolve().as_posix()
    ensure_dir(out_dir / "bd_tcl")
    script.write_text(
        f"""# Auto-generated. Run with the source Vivado version, for example 2020.2.
set source_xpr {{{manifest.source_project}}}
set bd_export_dir {{{bd_out}}}
file mkdir $bd_export_dir

open_project $source_xpr
set exported 0
foreach bd [get_files -quiet -filter {{FILE_TYPE == "Block Designs"}}] {{
    set bd_name [file rootname [file tail $bd]]
    open_bd_design $bd
    validate_bd_design
    write_bd_tcl -force [file join $bd_export_dir "${{bd_name}}.tcl"]
    close_bd_design [get_bd_designs $bd_name]
    incr exported
}}
report_ip_status -name ip_status -file [file join $bd_export_dir ip_status_source.rpt]
close_project
puts "Exported $exported block design Tcl file(s) to $bd_export_dir"
""",
        encoding="utf-8",
    )
    return script


def write_rebuild_tcl(manifest: ProjectManifest, out_dir: Path, new_project_dir: Path) -> Path:
    script = out_dir / "02_rebuild_project_in_target_vivado.tcl"
    project_dir = new_project_dir.resolve().as_posix()
    bd_dir = (out_dir / "bd_tcl").resolve().as_posix()
    hdl = tcl_list(manifest.hdl_files)
    xdc = tcl_list(manifest.xdc_files)
    xci = tcl_list(manifest.xci_files)
    top_line = f"set_property top {{{manifest.top}}} [current_fileset]" if manifest.top else "# Top is inferred after compile-order update."
    board_part_line = (
        f"set_property board_part {{{manifest.board_part}}} [current_project]"
        if manifest.board_part
        else "# Source project had no BoardPart property."
    )
    script.write_text(
        f"""# Auto-generated. Run with the target Vivado version, for example 2021.1.
set project_name {{{manifest.project_name}_migrated}}
set project_dir {{{project_dir}}}
set part {{{manifest.part}}}
set bd_export_dir {{{bd_dir}}}

file mkdir $project_dir
create_project $project_name $project_dir -part $part -force
{board_part_line}
set_property target_language {{{manifest.target_language}}} [current_project]
set_property simulator_language {{{manifest.simulator_language}}} [current_project]
set_property TARGET_SIMULATOR XSim [current_project]

set hdl_files [list {hdl}]
if {{[llength $hdl_files] > 0}} {{
    add_files -fileset sources_1 $hdl_files
}}

set xdc_files [list {xdc}]
if {{[llength $xdc_files] > 0}} {{
    add_files -fileset constrs_1 $xdc_files
}}

set xci_files [list {xci}]
if {{[llength $xci_files] > 0}} {{
    add_files -norecurse $xci_files
}}

foreach bd_tcl [glob -nocomplain [file join $bd_export_dir *.tcl]] {{
    if {{[file tail $bd_tcl] eq "ip_status_source.rpt"}} {{
        continue
    }}
    puts "Recreating block design from $bd_tcl"
    source $bd_tcl
    validate_bd_design
    save_bd_design
}}

foreach bd [get_files -quiet -filter {{FILE_TYPE == "Block Designs"}}] {{
    set wrapper [make_wrapper -files $bd -top]
    add_files -norecurse $wrapper
}}

if {{[llength [get_ips -quiet]] > 0}} {{
    report_ip_status -name ip_status_before_upgrade -file [file join $project_dir ip_status_before_upgrade.rpt]
    upgrade_ip -quiet [get_ips]
    generate_target all [get_ips]
    report_ip_status -name ip_status_after_upgrade -file [file join $project_dir ip_status_after_upgrade.rpt]
}}

update_compile_order -fileset sources_1
{top_line}
# Project changes are written by create_project/add_files in batch mode.
puts "Migrated project created at $project_dir/$project_name.xpr"
close_project
""",
        encoding="utf-8",
    )
    return script


def write_text(path: Path, content: str) -> Path:
    ensure_dir(path.parent)
    path.write_text(content, encoding="utf-8", newline="\n")
    return path


def write_basic_project_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / "create_project.tcl"
    project_dir = Path(args.project_dir).resolve().as_posix()
    src_dir = Path(args.src_dir).resolve().as_posix()
    sim_dir = Path(args.sim_dir).resolve().as_posix()
    xdc_dir = Path(args.xdc_dir).resolve().as_posix()
    board_xdc = resolve_board_xdc(args)
    ip_dir = Path(args.ip_dir).resolve().as_posix()
    bd_dir = Path(args.bd_dir).resolve().as_posix()
    top_line = f"set_property top {{{args.top}}} [current_fileset]" if args.top else "# Top is inferred by Vivado compile order."
    board_xdc_line = f"add_files -fileset constrs_1 {{{Path(board_xdc).resolve().as_posix()}}}" if board_xdc else "# No registered board XDC requested."
    return write_text(
        script,
        f"""# Auto-generated Vivado project creation Tcl.
set project_name {{{args.name}}}
set project_dir {{{project_dir}}}
set part {{{args.part}}}

create_project $project_name $project_dir -part $part -force
set_property target_language {{{args.language}}} [current_project]
set_property simulator_language Mixed [current_project]
set_property TARGET_SIMULATOR XSim [current_project]

foreach pattern [list {{{src_dir}/*.v}} {{{src_dir}/*.sv}} {{{src_dir}/*.vhd}} {{{src_dir}/*.vhdl}}] {{
    set files [glob -nocomplain $pattern]
    if {{[llength $files] > 0}} {{ add_files -fileset sources_1 $files }}
}}
foreach pattern [list {{{sim_dir}/*.v}} {{{sim_dir}/*.sv}} {{{sim_dir}/*.vhd}} {{{sim_dir}/*.vhdl}}] {{
    set files [glob -nocomplain $pattern]
    if {{[llength $files] > 0}} {{ add_files -fileset sim_1 $files }}
}}
set xdc_files [glob -nocomplain {{{xdc_dir}/*.xdc}}]
if {{[llength $xdc_files] > 0}} {{ add_files -fileset constrs_1 $xdc_files }}
{board_xdc_line}
set xci_files [glob -nocomplain {{{ip_dir}/*/*.xci}}]
if {{[llength $xci_files] > 0}} {{ add_files -norecurse $xci_files }}
set bd_files [glob -nocomplain {{{bd_dir}/*.bd}}]
if {{[llength $bd_files] > 0}} {{ add_files -norecurse $bd_files }}

update_compile_order -fileset sources_1
{top_line}
# Vivado 2020.2 treats "save_project" as an abbreviation for save_project_as.
# The project is already written by create_project/add_files in batch mode.
puts "Project created: $project_dir/$project_name.xpr"
close_project
""",
    )


def write_bd_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / "create_bd.tcl"
    xpr = Path(args.project).resolve().as_posix()
    bd_export = (out_dir / f"{args.bd_name}.tcl").resolve().as_posix()
    return write_text(
        script,
        f"""# Auto-generated BD Tcl. Zynq-7000 PS + AXI GPIO baseline.
open_project {{{xpr}}}
create_bd_design {{{args.bd_name}}}

create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7_0
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {{make_external "FIXED_IO, DDR"}} [get_bd_cells ps7_0]
set_property -dict [list \\
    CONFIG.PCW_USE_M_AXI_GP0 {{1}} \\
    CONFIG.PCW_FPGA_FCLK0_ENABLE {{1}} \\
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {{{args.clock_mhz}}} \\
] [get_bd_cells ps7_0]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins ps7_0/M_AXI_GP0_ACLK]

create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_ps7_0
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins rst_ps7_0/slowest_sync_clk]
connect_bd_net [get_bd_pins ps7_0/FCLK_RESET0_N] [get_bd_pins rst_ps7_0/ext_reset_in]
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 const_vcc
set_property CONFIG.CONST_VAL {{1}} [get_bd_cells const_vcc]
connect_bd_net [get_bd_pins const_vcc/dout] [get_bd_pins rst_ps7_0/dcm_locked]

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_ic_0
set_property -dict [list CONFIG.NUM_MI {{1}}] [get_bd_cells axi_ic_0]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_ic_0/ACLK]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_ic_0/S00_ACLK]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_ic_0/M00_ACLK]
connect_bd_net [get_bd_pins rst_ps7_0/interconnect_aresetn] [get_bd_pins axi_ic_0/ARESETN]
connect_bd_net [get_bd_pins rst_ps7_0/peripheral_aresetn] [get_bd_pins axi_ic_0/S00_ARESETN]
connect_bd_net [get_bd_pins rst_ps7_0/peripheral_aresetn] [get_bd_pins axi_ic_0/M00_ARESETN]
connect_bd_intf_net [get_bd_intf_pins ps7_0/M_AXI_GP0] [get_bd_intf_pins axi_ic_0/S00_AXI]

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0
set_property -dict [list CONFIG.C_GPIO_WIDTH {{{args.gpio_width}}} CONFIG.C_ALL_OUTPUTS {{1}}] [get_bd_cells axi_gpio_0]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_gpio_0/s_axi_aclk]
connect_bd_net [get_bd_pins rst_ps7_0/peripheral_aresetn] [get_bd_pins axi_gpio_0/s_axi_aresetn]
connect_bd_intf_net [get_bd_intf_pins axi_ic_0/M00_AXI] [get_bd_intf_pins axi_gpio_0/S_AXI]
make_bd_intf_pins_external [get_bd_intf_pins axi_gpio_0/GPIO]
set_property name gpio_0 [get_bd_intf_ports GPIO_0]

assign_bd_address
validate_bd_design
save_bd_design
write_bd_tcl -force {{{bd_export}}}
set wrapper [make_wrapper -files [get_files {{{args.bd_name}.bd}}] -top]
add_files -norecurse $wrapper
set_property top {{{args.bd_name}_wrapper}} [current_fileset]
update_compile_order -fileset sources_1
# Project changes are written by the preceding BD/add_files commands.
close_project
""",
    )


def write_run_flow_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / f"run_{args.step}.tcl"
    xpr = Path(args.project).resolve().as_posix()
    reports = Path(args.reports_dir).resolve().as_posix()
    checkpoints = Path(args.checkpoint_dir).resolve().as_posix()
    body = f"""open_project {{{xpr}}}
"""
    if args.step in {"synthesis", "implementation"}:
        body += f"""
file mkdir {{{reports}}}
file mkdir {{{checkpoints}}}
"""
    if args.step == "synthesis":
        body += f"""
set_property strategy {{{args.strategy}}} [get_runs synth_1]
launch_runs synth_1 -jobs {args.jobs}
wait_on_run synth_1
open_run synth_1
report_timing_summary -delay_type max -max_paths 20 -file {{{reports}/post_synth_timing.rpt}}
report_utilization -file {{{reports}/post_synth_utilization.rpt}}
report_power -file {{{reports}/post_synth_power.rpt}}
write_checkpoint -force {{{checkpoints}/post_synth.dcp}}
"""
    elif args.step == "implementation":
        body += f"""
set_property strategy {{{args.strategy}}} [get_runs impl_1]
launch_runs impl_1 -jobs {args.jobs}
wait_on_run impl_1
open_run impl_1
report_timing_summary -delay_type min_max -max_paths 20 -file {{{reports}/post_route_timing.rpt}}
report_utilization -hierarchical -file {{{reports}/post_route_utilization.rpt}}
report_power -file {{{reports}/post_route_power.rpt}}
report_drc -file {{{reports}/post_route_drc.rpt}}
write_checkpoint -force {{{checkpoints}/post_route.dcp}}
"""
    elif args.step == "bitstream":
        body += f"""
set impl_status [get_property STATUS [get_runs impl_1]]
launch_runs impl_1 -to_step write_bitstream -jobs {args.jobs}
wait_on_run impl_1
open_run impl_1
set impl_dir [get_property DIRECTORY [get_runs impl_1]]
set bit_files [glob -nocomplain [file join $impl_dir *.bit]]
if {{[llength $bit_files] == 0}} {{ error "Implementation completed, but no .bit file was found in $impl_dir" }}
puts "Bitstream: [lindex $bit_files 0]"
"""
    body += "# Flow reports/checkpoints are already written explicitly.\nclose_project\n"
    return write_text(script, "# Auto-generated Vivado flow Tcl.\n" + body)


def write_simulation_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / "run_simulation.tcl"
    xpr = Path(args.project).resolve().as_posix()
    results = Path(args.results_dir).resolve().as_posix()
    return write_text(
        script,
        f"""# Auto-generated XSim Tcl.
open_project {{{xpr}}}
file mkdir {{{results}}}
set_property TARGET_SIMULATOR XSim [current_project]
set_property top {{{args.top}}} [get_filesets sim_1]
set_property -name {{xsim.simulate.runtime}} -value {{{args.runtime}}} -objects [get_filesets sim_1]
launch_simulation
add_wave -r /*
run {{{args.runtime}}}
save_wave_config {{{results}/{args.top}.wcfg}}
close_sim
close_project
""",
    )


def write_ip_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / "ip.tcl"
    xpr = Path(args.project).resolve().as_posix()
    ip_dir = Path(args.ip_dir).resolve().as_posix()
    props = " ".join(item for item in args.config)
    if args.ip_action == "create":
        body = f"""
open_project {{{xpr}}}
file mkdir {{{ip_dir}}}
create_ip -name {{{args.ip_name}}} -vendor xilinx.com -library ip -module_name {{{args.module_name}}} -dir {{{ip_dir}}}
"""
        if args.version:
            body = body.replace(" -module_name ", f" -version {{{args.version}}} -module_name ")
        if props:
            body += f"set_property -dict [list {props}] [get_ips {{{args.module_name}}}]\n"
        body += f"""generate_target all [get_ips {{{args.module_name}}}]
export_ip_user_files -of_objects [get_ips {{{args.module_name}}}] -no_script -sync -force -quiet
# IP files and output products are written explicitly.
close_project
"""
    else:
        body = f"""open_project {{{xpr}}}
set ip [get_ips {{{args.module_name}}}]
"""
        if props:
            body += f"set_property -dict [list {props}] $ip\n"
        body += """reset_target all $ip
generate_target all $ip
report_ip_status -name ip_status
# IP files and output products are written explicitly.
close_project
"""
    return write_text(script, "# Auto-generated IP Tcl.\n" + body)


def write_output_products_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / "generate_output_products.tcl"
    xpr = Path(args.project).resolve().as_posix()
    return write_text(
        script,
        f"""# Auto-generated output product Tcl.
open_project {{{xpr}}}
set objects [concat [get_ips -quiet] [get_files -quiet -filter {{FILE_TYPE == "Block Designs"}}]]
if {{[llength $objects] == 0}} {{
    puts "No IP or BD objects found."
}} else {{
    generate_target all $objects
    export_ip_user_files -of_objects $objects -no_script -sync -force -quiet
}}
# Output products are written explicitly.
close_project
""",
    )


def write_program_device_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    script = out_dir / "program_device.tcl"
    bit_file = Path(args.bit_file).resolve().as_posix()
    probes_line = ""
    if args.ltx_file:
        probes_line = f"set_property PROBES.FILE {{{Path(args.ltx_file).resolve().as_posix()}}} $device"
    return write_text(
        script,
        f"""# Auto-generated hardware open/program Tcl.
open_hw_manager
connect_hw_server -url {{{args.hw_server_url}}}
set targets [get_hw_targets -quiet]
if {{[llength $targets] == 0}} {{
    error "No hardware targets found. Check cable, board power, and hw_server."
}}
current_hw_target [lindex $targets 0]
open_hw_target
set devices [get_hw_devices -quiet]
if {{[llength $devices] == 0}} {{
    error "No hardware devices found on the selected target."
}}
set programmable_devices [list]
foreach candidate $devices {{
    if {{[get_property PROGRAM.IS_SUPPORTED $candidate]}} {{
        lappend programmable_devices $candidate
    }}
}}
if {{[llength $programmable_devices] == 0}} {{
    error "No programmable FPGA devices found. Detected devices: $devices"
}}
set device [lindex $programmable_devices {args.device_index}]
current_hw_device $device
refresh_hw_device $device
set_property PROGRAM.FILE {{{bit_file}}} $device
{probes_line}
program_hw_devices $device
puts "Programmed device with {bit_file}"
close_hw_target
close_hw_manager
""",
    )


def write_hard_rtl_workflow_tcl(args: argparse.Namespace, out_dir: Path) -> Path:
    """Write one ordered Tcl state machine for a complete Vivado project flow."""
    script = out_dir / "run_workflow.tcl"
    root = Path(args.root).resolve()
    project_dir = root.resolve().as_posix()
    parent_dir = root.parent.resolve().as_posix()
    src_dir = workflow_path(root, args.src_dir).as_posix()
    sim_dir = workflow_path(root, args.sim_dir).as_posix()
    xdc_dir = workflow_path(root, args.xdc_dir).as_posix()
    bd_mode = args.bd_mode
    xdc_lines = []
    if args.xdc:
        xdc_path = workflow_path(root, args.xdc)
        xdc_lines.append(
            f"""if {{![file exists {{{xdc_path.as_posix()}}}]}} {{ va_fail "Requested XDC does not exist: {xdc_path.as_posix()}" }}
add_files -fileset constrs_1 {{{xdc_path.as_posix()}}}"""
        )
    board_xdc = resolve_board_xdc(args)
    if board_xdc:
        board_xdc_path = Path(board_xdc).resolve().as_posix()
        xdc_lines.append(
            f"""if {{![file exists {{{board_xdc_path}}}]}} {{ va_fail "Registered board XDC does not exist: {board_xdc_path}" }}
add_files -fileset constrs_1 {{{board_xdc_path}}}"""
        )
    xdc_block = "\n".join(xdc_lines) if xdc_lines else 'puts "No explicit XDC files requested."'
    xdc_glob_block = f"""set xdc_files [glob -nocomplain {{{xdc_dir}/*.xdc}}]
if {{[llength $xdc_files] > 0}} {{ add_files -fileset constrs_1 $xdc_files }}
{xdc_block}
update_compile_order -fileset sources_1"""
    effective_board_part = resolve_board_part(args)
    board_part_line = ""
    if effective_board_part:
        board_part_line = f"""
set_property board_part {{{effective_board_part}}} [current_project]
va_assert_project_property board_part {{{effective_board_part}}}
"""

    top_line = f"set_property top {{{args.top}}} [current_fileset]" if args.top else "# top inferred"
    pl_rtl_block = ""
    bd_block = ""
    export_hw = "1" if args.export_hw else "0"
    uart_props = {
        "none": "",
        "uart0": (
            "CONFIG.PCW_UART0_PERIPHERAL_ENABLE {1} "
            "CONFIG.PCW_UART0_UART0_IO {MIO 14 .. 15} "
            "CONFIG.PCW_UART0_GRP_FULL_ENABLE {0} "
            "CONFIG.PCW_UART0_BAUD_RATE {115200} "
            "CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {50}"
        ),
        "uart1": (
            "CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} "
            "CONFIG.PCW_UART1_UART1_IO {MIO 48 .. 49} "
            "CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} "
            "CONFIG.PCW_UART1_BAUD_RATE {115200} "
            "CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {50}"
        ),
    }[args.ps_uart]
    ps_uart_property_tcl = (
        f"set_property -dict [list {uart_props}] [get_bd_cells ps7_0]"
        if uart_props
        else 'puts "No PS UART requested."'
    )
    ps_uart_assert_tcl = (
        f"va_assert_ps_uart ps7_0 {args.ps_uart}"
        if args.ps_uart != "none"
        else 'puts "No PS UART assertion requested."'
    )
    if bd_mode == "none":
        pl_rtl_block = f"""
va_phase "pl_add_verilog"
set src_count 0
foreach pattern [list {{{src_dir}/*.v}} {{{src_dir}/*.sv}} {{{src_dir}/*.vhd}} {{{src_dir}/*.vhdl}}] {{
    set files [glob -nocomplain $pattern]
    if {{[llength $files] > 0}} {{
        add_files -fileset sources_1 $files
        incr src_count [llength $files]
    }}
}}
if {{$src_count == 0}} {{ va_fail "No HDL files found in {src_dir}; refusing to run an empty PL RTL flow." }}
foreach pattern [list {{{sim_dir}/*.v}} {{{sim_dir}/*.sv}} {{{sim_dir}/*.vhd}} {{{sim_dir}/*.vhdl}}] {{
    set files [glob -nocomplain $pattern]
    if {{[llength $files] > 0}} {{ add_files -fileset sim_1 $files }}
}}
{top_line}
update_compile_order -fileset sources_1
va_phase "pl_design_review"
va_assert_project_top
report_compile_order -fileset sources_1

va_phase "pl_add_xdc"
{xdc_glob_block}
"""
    elif bd_mode == "zynq-ps":
        bd_block = f"""
va_phase "bd_create_connect_validate"
create_bd_design {{{args.bd_name}}}
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7_0
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {{make_external "FIXED_IO, DDR"}} [get_bd_cells ps7_0]
{ps_uart_property_tcl}
set_property -dict [list CONFIG.PCW_USE_M_AXI_GP0 {{0}} CONFIG.PCW_FPGA_FCLK0_ENABLE {{1}} CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {{{args.clock_mhz}}}] [get_bd_cells ps7_0]
va_phase "bd_design_review"
va_assert_bd_cell ps7_0
va_assert_bd_intf_port DDR
va_assert_bd_intf_port FIXED_IO
va_assert_bd_intf_pin_connected ps7_0/DDR
va_assert_bd_intf_pin_connected ps7_0/FIXED_IO
va_assert_bd_pin_connected ps7_0/FCLK_CLK0
{ps_uart_assert_tcl}
validate_bd_design
save_bd_design
write_bd_tcl -force [file join {{{out_dir.resolve().as_posix()}}} {{{args.bd_name}.tcl}}]

va_phase "bd_output_products"
set bd_objects [get_files -quiet -filter {{FILE_TYPE == "Block Designs"}}]
if {{[llength $bd_objects] == 0}} {{ va_fail "No block design objects found after BD creation." }}
generate_target all $bd_objects
export_ip_user_files -of_objects $bd_objects -no_script -sync -force -quiet

va_phase "bd_generate_wrapper"
set wrapper [make_wrapper -files [get_files {{{args.bd_name}.bd}}] -top]
add_files -norecurse $wrapper
set_property top {{{args.bd_name}_wrapper}} [current_fileset]
update_compile_order -fileset sources_1

va_phase "bd_add_xdc"
{xdc_glob_block}
"""
    elif bd_mode == "zynq-axi-gpio":
        gpio_props = (
            f"CONFIG.C_GPIO_WIDTH {{{args.gpio_width}}} CONFIG.C_ALL_INPUTS {{1}} CONFIG.C_IS_DUAL {{0}}"
            if args.gpio_direction == "input"
            else f"CONFIG.C_GPIO_WIDTH {{{args.gpio_width}}} CONFIG.C_ALL_OUTPUTS {{1}} CONFIG.C_IS_DUAL {{0}}"
        )
        bd_block = f"""
va_phase "bd_create_connect_validate"
create_bd_design {{{args.bd_name}}}
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7_0
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \\
    -config {{make_external "FIXED_IO, DDR"}} [get_bd_cells ps7_0]
set_property -dict [list CONFIG.PCW_USE_M_AXI_GP0 {{1}} CONFIG.PCW_FPGA_FCLK0_ENABLE {{1}} CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {{{args.clock_mhz}}}] [get_bd_cells ps7_0]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins ps7_0/M_AXI_GP0_ACLK]

create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_ps7_0
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins rst_ps7_0/slowest_sync_clk]
connect_bd_net [get_bd_pins ps7_0/FCLK_RESET0_N] [get_bd_pins rst_ps7_0/ext_reset_in]
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 const_vcc
set_property CONFIG.CONST_VAL {{1}} [get_bd_cells const_vcc]
connect_bd_net [get_bd_pins const_vcc/dout] [get_bd_pins rst_ps7_0/dcm_locked]

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_ic_0
set_property -dict [list CONFIG.NUM_MI {{1}}] [get_bd_cells axi_ic_0]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_ic_0/ACLK]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_ic_0/S00_ACLK]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_ic_0/M00_ACLK]
connect_bd_net [get_bd_pins rst_ps7_0/interconnect_aresetn] [get_bd_pins axi_ic_0/ARESETN]
connect_bd_net [get_bd_pins rst_ps7_0/peripheral_aresetn] [get_bd_pins axi_ic_0/S00_ARESETN]
connect_bd_net [get_bd_pins rst_ps7_0/peripheral_aresetn] [get_bd_pins axi_ic_0/M00_ARESETN]
connect_bd_intf_net [get_bd_intf_pins ps7_0/M_AXI_GP0] [get_bd_intf_pins axi_ic_0/S00_AXI]

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0
set_property -dict [list {gpio_props}] [get_bd_cells axi_gpio_0]
connect_bd_net [get_bd_pins ps7_0/FCLK_CLK0] [get_bd_pins axi_gpio_0/s_axi_aclk]
connect_bd_net [get_bd_pins rst_ps7_0/peripheral_aresetn] [get_bd_pins axi_gpio_0/s_axi_aresetn]
connect_bd_intf_net [get_bd_intf_pins axi_ic_0/M00_AXI] [get_bd_intf_pins axi_gpio_0/S_AXI]
make_bd_intf_pins_external [get_bd_intf_pins axi_gpio_0/GPIO]
set_property name {{{args.gpio_port_name}}} [get_bd_intf_ports GPIO_0]
assign_bd_address
va_phase "bd_design_review"
va_assert_bd_cell ps7_0
va_assert_bd_cell rst_ps7_0
va_assert_bd_cell axi_ic_0
va_assert_bd_cell axi_gpio_0
va_assert_bd_intf_port DDR
va_assert_bd_intf_port FIXED_IO
va_assert_bd_intf_port {{{args.gpio_port_name}}}
va_assert_bd_pin_connected ps7_0/FCLK_CLK0
va_assert_bd_pin_connected ps7_0/M_AXI_GP0_ACLK
va_assert_bd_pin_connected rst_ps7_0/slowest_sync_clk
va_assert_bd_pin_connected rst_ps7_0/dcm_locked
va_assert_bd_pin_connected axi_gpio_0/s_axi_aclk
va_assert_bd_pin_connected axi_gpio_0/s_axi_aresetn
va_assert_bd_intf_pin_connected ps7_0/M_AXI_GP0
va_assert_bd_intf_pin_connected axi_ic_0/S00_AXI
va_assert_bd_intf_pin_connected axi_ic_0/M00_AXI
va_assert_bd_intf_pin_connected axi_gpio_0/S_AXI
va_assert_bd_intf_pin_connected axi_gpio_0/GPIO
va_assert_bd_addressed
validate_bd_design
save_bd_design
write_bd_tcl -force [file join {{{out_dir.resolve().as_posix()}}} {{{args.bd_name}.tcl}}]

va_phase "bd_output_products"
set bd_objects [get_files -quiet -filter {{FILE_TYPE == "Block Designs"}}]
if {{[llength $bd_objects] == 0}} {{ va_fail "No block design objects found after BD creation." }}
generate_target all $bd_objects
export_ip_user_files -of_objects $bd_objects -no_script -sync -force -quiet

va_phase "bd_generate_wrapper"
set wrapper [make_wrapper -files [get_files {{{args.bd_name}.bd}}] -top]
add_files -norecurse $wrapper
set_property top {{{args.bd_name}_wrapper}} [current_fileset]
update_compile_order -fileset sources_1

va_phase "bd_add_xdc"
{xdc_glob_block}
"""

    return write_text(
        script,
        f"""# HARD Vivado workflow Tcl. Do not edit by hand; regenerate from vivado_assistant.py.
set root_dir {{{root.as_posix()}}}
set parent_dir {{{parent_dir}}}
set project_name {{{args.name}}}
set project_dir {{{project_dir}}}
set part {{{args.part}}}

proc va_phase {{name}} {{
    puts "\\n===== VA_PHASE $name ====="
}}
proc va_fail {{message}} {{
    puts "VA_ERROR: $message"
    error $message
}}
proc va_assert_run_ok {{run_name}} {{
    set status [get_property STATUS [get_runs $run_name]]
    set progress [get_property PROGRESS [get_runs $run_name]]
    puts "Run $run_name status=$status progress=$progress"
    if {{![string match "*Complete*" $status] && ![string match "100%" $progress]}} {{
        va_fail "Run $run_name did not complete: $status / $progress"
    }}
}}
proc va_assert_project_property {{prop expected}} {{
    set actual [get_property $prop [current_project]]
    puts "Project property check: $prop=$actual"
    if {{$actual ne $expected}} {{ va_fail "Project property $prop expected '$expected' but got '$actual'" }}
}}
proc va_assert_bd_pin_connected {{pin_name}} {{
    set pins [get_bd_pins -quiet $pin_name]
    if {{[llength $pins] == 0}} {{ va_fail "Required BD pin not found: $pin_name" }}
    set nets [get_bd_nets -quiet -of_objects $pins]
    if {{[llength $nets] == 0}} {{ va_fail "Required BD pin is not connected: $pin_name" }}
}}
proc va_assert_project_top {{}} {{
    set top [get_property top [current_fileset]]
    puts "Project top check: $top"
    if {{$top eq ""}} {{ va_fail "No top module/entity is selected after HDL insertion." }}
}}
proc va_assert_bd_cell {{cell_name}} {{
    set cells [get_bd_cells -quiet $cell_name]
    if {{[llength $cells] == 0}} {{ va_fail "Required BD cell not found: $cell_name" }}
}}
proc va_assert_bd_intf_port {{port_name}} {{
    set ports [get_bd_intf_ports -quiet $port_name]
    if {{[llength $ports] == 0}} {{ va_fail "Required BD interface port not found: $port_name" }}
}}
proc va_assert_bd_intf_pin_connected {{pin_name}} {{
    set pins [get_bd_intf_pins -quiet $pin_name]
    if {{[llength $pins] == 0}} {{ va_fail "Required BD interface pin not found: $pin_name" }}
    set nets [get_bd_intf_nets -quiet -of_objects $pins]
    if {{[llength $nets] == 0}} {{ va_fail "Required BD interface pin is not connected: $pin_name" }}
}}
proc va_assert_bd_addressed {{}} {{
    set segs [get_bd_addr_segs -quiet]
    puts "BD address segment count: [llength $segs]"
    if {{[llength $segs] == 0}} {{ va_fail "No BD address segments found after assign_bd_address." }}
}}
proc va_assert_ps_uart {{cell_name uart_name}} {{
    set cells [get_bd_cells -quiet $cell_name]
    if {{[llength $cells] == 0}} {{ va_fail "Required PS cell not found: $cell_name" }}
    if {{$uart_name eq "uart0"}} {{
        set enable_prop CONFIG.PCW_UART0_PERIPHERAL_ENABLE
        set io_prop CONFIG.PCW_UART0_UART0_IO
    }} elseif {{$uart_name eq "uart1"}} {{
        set enable_prop CONFIG.PCW_UART1_PERIPHERAL_ENABLE
        set io_prop CONFIG.PCW_UART1_UART1_IO
    }} else {{
        va_fail "Unsupported PS UART assertion: $uart_name"
    }}
    set enabled [get_property $enable_prop $cells]
    set io [get_property $io_prop $cells]
    puts "PS UART check: $uart_name enabled=$enabled io=$io"
    if {{$enabled ne "1"}} {{ va_fail "$uart_name is required by design intent but is not enabled on $cell_name" }}
    if {{$io eq ""}} {{ va_fail "$uart_name is enabled but has no MIO assignment on $cell_name" }}
}}

file mkdir $parent_dir
cd $parent_dir

va_phase "create_project"
create_project $project_name $project_dir -part $part -force
{board_part_line}
set_property target_language {{{args.language}}} [current_project]
set_property simulator_language Mixed [current_project]
set_property TARGET_SIMULATOR XSim [current_project]

{pl_rtl_block}
{bd_block}

va_phase "synthesis"
set_property strategy {{{args.synth_strategy}}} [get_runs synth_1]
launch_runs synth_1 -jobs {args.jobs}
wait_on_run synth_1
va_assert_run_ok synth_1
open_run synth_1
report_timing_summary -delay_type max -max_paths 20
report_utilization

va_phase "implementation_bitstream"
set_property strategy {{{args.impl_strategy}}} [get_runs impl_1]
launch_runs impl_1 -to_step write_bitstream -jobs {args.jobs}
wait_on_run impl_1
va_assert_run_ok impl_1
open_run impl_1
report_timing_summary -delay_type min_max -max_paths 20
report_utilization -hierarchical
report_drc
set impl_dir [get_property DIRECTORY [get_runs impl_1]]
set bit_files [glob -nocomplain [file join $impl_dir *.bit]]
if {{[llength $bit_files] == 0}} {{ va_fail "Vivado implementation completed, but no .bit file was found in $impl_dir" }}
puts "Bitstream: [lindex $bit_files 0]"

va_phase "hardware_export"
if {{{export_hw}}} {{
    write_hw_platform -fixed -include_bit -force -file [file join $project_dir {{{args.name}.xsa}}]
}}

va_phase "done"
puts "Workflow complete under $root_dir"
close_project
""",
    )


def collect_vivado_diagnostics(log_paths: Iterable[Path]) -> str:
    patterns = [
        re.compile(r"VA_PHASE", re.IGNORECASE),
        re.compile(r"VA_ERROR", re.IGNORECASE),
        re.compile(r"\bERROR:", re.IGNORECASE),
        re.compile(r"CRITICAL WARNING", re.IGNORECASE),
        re.compile(r"failed|no such file|invalid command|cannot|can't", re.IGNORECASE),
    ]
    lines: list[str] = []
    seen: set[tuple[str, int]] = set()
    for log_path in log_paths:
        if not log_path.exists() or not log_path.is_file():
            continue
        try:
            content = log_path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        for idx, line in enumerate(content, start=1):
            if any(pattern.search(line) for pattern in patterns):
                key = (str(log_path), idx)
                if key not in seen:
                    seen.add(key)
                    lines.append(f"{log_path}:{idx}: {line}")
    if not lines:
        return "No obvious ERROR/CRITICAL WARNING/VA_ERROR lines found in collected logs."
    return "\n".join(lines[-120:])


def write_debug_summary(root: Path, automation: Path, extra_logs: Iterable[Path]) -> Path:
    log_paths = [
        automation / "vivado_run.log",
        root / "vivado.log",
        root / "vivado.jou",
        *extra_logs,
    ]
    summary = automation / "debug_summary.txt"
    body = [
        "Vivado Automation Debug Summary",
        f"root: {root}",
        f"last_phase: {read_last_phase(automation)}",
        "",
        "Key log lines:",
        collect_vivado_diagnostics(log_paths),
        "",
        "Checked logs:",
        *[str(path) for path in log_paths if path.exists()],
        "",
    ]
    xsa_report = automation / "xsa_inspection.json"
    if xsa_report.exists():
        body.extend(["XSA inspection:", xsa_report.read_text(encoding="utf-8", errors="replace"), ""])
    write_text(summary, "\n".join(body))
    return summary


def inspect_xsa(xsa: Path) -> dict:
    if not xsa.exists():
        raise RuntimeError(f"Expected XSA was not created: {xsa}")
    try:
        with zipfile.ZipFile(xsa) as archive:
            names = archive.namelist()
    except zipfile.BadZipFile as exc:
        raise RuntimeError(f"XSA is not a readable zip archive: {xsa}") from exc
    bit_files = [name for name in names if name.lower().endswith(".bit")]
    hwh_files = [name for name in names if name.lower().endswith(".hwh")]
    xsa_info = {
        "xsa": str(xsa),
        "entry_count": len(names),
        "bit_files": bit_files,
        "hwh_files": hwh_files,
    }
    if not bit_files:
        raise RuntimeError(f"XSA does not contain a bitstream. Re-export with write_hw_platform -include_bit: {xsa}")
    if not hwh_files:
        raise RuntimeError(f"XSA does not contain an HWH hardware handoff file: {xsa}")
    return xsa_info


def verify_exported_hardware(root: Path, name: str, automation: Path) -> Path:
    xsa = root / f"{name}.xsa"
    info = inspect_xsa(xsa)
    report = automation / "xsa_inspection.json"
    write_text(report, json.dumps(info, indent=2))
    print(f"Verified XSA contains bitstream and HWH: {xsa}")
    return report


def read_last_phase(automation: Path) -> str:
    phase_file = automation / "last_phase.txt"
    if phase_file.exists():
        return phase_file.read_text(encoding="utf-8", errors="replace").strip()
    return "unknown"


def hard_rtl_workflow_cmd(args: argparse.Namespace) -> int:
    if not args.run and not args.plan_only:
        raise SystemExit("run-rtl-workflow is an execution command. Pass --run, or pass --plan-only only for dry planning.")
    if args.plan_only and args.run:
        raise SystemExit("Use either --run or --plan-only, not both.")
    root = Path(args.root).resolve()
    automation = Path(args.automation_dir).resolve() if args.automation_dir else Path(tempfile.gettempdir()) / "vivado_assistant" / args.name
    ensure_dir(automation)
    manifest = {
        "workflow": "hard-rtl",
        "name": args.name,
        "vivado_project_dir": str(root),
        "part": args.part,
        "board_part": resolve_board_part(args),
        "bd_mode": args.bd_mode,
        "src_dir": str(workflow_path(root, args.src_dir)),
        "xdc_dir": str(workflow_path(root, args.xdc_dir)),
        "vivado_version": args.vivado_version,
        "automation_dir": str(automation),
    }
    write_text(automation / "workflow_manifest.json", json.dumps(manifest, indent=2))
    tcl = write_hard_rtl_workflow_tcl(args, automation)
    vivado = resolve_vivado(args, args.vivado_version)
    print(f"Wrote manifest: {automation / 'workflow_manifest.json'}")
    print(f"Wrote hard workflow Tcl: {tcl}")
    print(f"Resolved Vivado: {vivado}")
    if args.run:
        require_host_can_run(vivado)
        try:
            run_vivado(vivado, tcl, root.parent, automation / "vivado_run.log", automation / "stage_logs")
            if args.export_hw:
                verify_exported_hardware(root, args.name, automation)
            summary = write_debug_summary(root, automation, [])
            print(f"Wrote debug summary: {summary}")
        except subprocess.CalledProcessError as exc:
            summary = write_debug_summary(root, automation, [])
            print(f"Wrote debug summary: {summary}")
            raise SystemExit(exc.returncode)
        except RuntimeError as exc:
            print(f"VA_ERROR: {exc}")
            summary = write_debug_summary(root, automation, [])
            print(f"Wrote debug summary: {summary}")
            raise SystemExit(1)
    else:
        print("Plan-only mode: no Vivado execution was requested.")
    return 0


def doctor_cmd(args: argparse.Namespace) -> int:
    print(f"Host OS: {platform.system()} {platform.release()}")
    config = load_config(args.assistant_config)
    if config:
        print(f"Config: {Path(args.assistant_config).resolve()}")
        for key, value in configured_vivados(config).items():
            resolved, notes = resolve_vivado_launcher(value)
            print(f"{key}: {value}")
            print(f"  resolved: {resolved}")
            for note in notes:
                print(f"  WARNING: {note}")
    for candidate in args.vivado_candidate:
        resolved, notes = resolve_vivado_launcher(candidate)
        print(f"candidate: {candidate}")
        print(f"  resolved: {resolved}")
        for note in notes:
            print(f"  WARNING: {note}")
    return 0


def make_and_maybe_run(script: Path, vivado: str, run: bool, cwd: Path) -> int:
    print(f"Wrote Tcl: {script}")
    if run:
        require_host_can_run(vivado)
        run_vivado(vivado, script, cwd)
    else:
        print(f"Next: {vivado} -mode batch -source {script}")
    return 0


def create_project_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    return make_and_maybe_run(write_basic_project_tcl(args, out_dir), resolve_vivado(args), args.run, out_dir)


def create_bd_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    return make_and_maybe_run(write_bd_tcl(args, out_dir), resolve_vivado(args), args.run, out_dir)


def run_flow_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    vivado = resolve_vivado(args)
    make_and_maybe_run(write_run_flow_tcl(args, out_dir), vivado, args.run, out_dir)
    if args.step == "bitstream" and args.run:
        bit_file = find_standard_impl_bit(Path(args.project).resolve())
        should_program = getattr(args, "program_device", False)
        if getattr(args, "ask_program_device", False):
            answer = input(f"Bitstream generated at {bit_file}. Open hardware and program device? [y/N] ")
            should_program = answer.strip().lower() in {"y", "yes"}
        if should_program:
            program_args = argparse.Namespace(
                bit_file=str(bit_file),
                ltx_file=getattr(args, "ltx_file", ""),
                hw_server_url=getattr(args, "hw_server_url", "localhost:3121"),
                device_index=getattr(args, "device_index", 0),
                out=str(out_dir),
                vivado=getattr(args, "vivado", ""),
                assistant_config=getattr(args, "assistant_config", None),
                run=True,
            )
            program_device_cmd(program_args)
    return 0


def simulate_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    return make_and_maybe_run(write_simulation_tcl(args, out_dir), resolve_vivado(args), args.run, out_dir)


def ip_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    return make_and_maybe_run(write_ip_tcl(args, out_dir), resolve_vivado(args), args.run, out_dir)


def output_products_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    return make_and_maybe_run(write_output_products_tcl(args, out_dir), resolve_vivado(args), args.run, out_dir)


def program_device_cmd(args: argparse.Namespace) -> int:
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    return make_and_maybe_run(write_program_device_tcl(args, out_dir), resolve_vivado(args), args.run, out_dir)


def stage_log_name(stage: str, index: int) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", stage).strip("_") or "unknown"
    return f"{index:02d}_{safe}.log"


def run_vivado(vivado: str, script: Path, cwd: Path, log_path: Path | None = None, stage_log_dir: Path | None = None) -> None:
    cmd = [vivado, "-mode", "batch", "-source", str(script)]
    print("+ " + " ".join(cmd))
    if log_path:
        ensure_dir(log_path.parent)
        stage_log = None
        stage_index = 0
        current_stage = "startup"
        if stage_log_dir:
            ensure_dir(stage_log_dir)
        with log_path.open("w", encoding="utf-8", errors="replace") as log:
            log.write("+ " + " ".join(cmd) + "\n")
            process = subprocess.Popen(
                cmd,
                cwd=str(cwd),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
            assert process.stdout is not None
            for line in process.stdout:
                match = re.search(r"===== VA_PHASE ([^=]+) =====", line)
                if match and stage_log_dir:
                    if stage_log:
                        stage_log.close()
                    stage_index += 1
                    current_stage = match.group(1).strip()
                    (log_path.parent / "last_phase.txt").write_text(current_stage, encoding="utf-8")
                    stage_log = (stage_log_dir / stage_log_name(current_stage, stage_index)).open(
                        "w", encoding="utf-8", errors="replace"
                    )
                print(line, end="")
                log.write(line)
                if stage_log:
                    stage_log.write(line)
            return_code = process.wait()
        if stage_log:
            stage_log.close()
        if stage_log_dir and current_stage == "startup":
            (log_path.parent / "last_phase.txt").write_text(current_stage, encoding="utf-8")
        if return_code != 0:
            raise subprocess.CalledProcessError(return_code, cmd)
        return
    subprocess.run(cmd, cwd=str(cwd), check=True)


def migrate_project(args: argparse.Namespace) -> int:
    project = Path(args.project).resolve()
    out_dir = Path(args.out).resolve()
    ensure_dir(out_dir)
    config = load_config(args.assistant_config)
    default_vivado = resolve_vivado(args)
    source_vivado = resolve_versioned_vivado(
        config,
        args.source_vivado,
        args.source_version,
        role="source",
        fallback=default_vivado,
    )
    target_vivado = resolve_versioned_vivado(
        config,
        args.target_vivado,
        args.target_version,
        role="target",
        fallback=default_vivado,
    )

    manifest = manifest_from_project(project)
    manifest_path = out_dir / "migration_manifest.json"
    manifest_path.write_text(json.dumps(asdict(manifest), indent=2), encoding="utf-8")

    export_tcl = write_export_tcl(manifest, out_dir)
    rebuild_tcl = write_rebuild_tcl(manifest, out_dir, Path(args.new_project_dir).resolve())

    print(f"Wrote manifest: {manifest_path}")
    print(f"Wrote source export Tcl: {export_tcl}")
    print(f"Wrote target rebuild Tcl: {rebuild_tcl}")

    if args.run_export:
        require_host_can_run(source_vivado)
        run_vivado(source_vivado, export_tcl, out_dir)
    if args.run_rebuild:
        require_host_can_run(target_vivado)
        run_vivado(target_vivado, rebuild_tcl, out_dir)

    if not args.run_export or not args.run_rebuild:
        print("Next (advanced/debug fallback; prefer --run-export --run-rebuild for normal automation):")
        print(f"  {source_vivado} -mode batch -source {export_tcl}")
        print(f"  {target_vivado} -mode batch -source {rebuild_tcl}")
    return 0


def find_bsp_makefiles(root: Path) -> list[Path]:
    candidates: list[Path] = []
    for path in root.rglob("Makefile"):
        if should_ignore(path):
            continue
        if is_bsp_root_makefile(path):
            candidates.append(path.resolve())
    return sorted(set(candidates))


def is_bsp_root_makefile(path: Path) -> bool:
    if path.name != "Makefile":
        return False
    parts = [part.lower() for part in path.parts]
    if "libsrc" in parts and "src" in parts:
        return False
    return path.parent.name.endswith("_bsp") or "zynq_fsbl_bsp" in parts


def patch_vitis_makefile(args: argparse.Namespace) -> int:
    root = Path(args.workspace).resolve()
    makefiles = [Path(args.makefile).resolve()] if args.makefile else find_bsp_makefiles(root)
    if not makefiles:
        raise FileNotFoundError(f"No BSP Makefile found under {root}")
    for makefile in makefiles:
        if not is_bsp_root_makefile(makefile):
            raise SystemExit(f"Refusing to patch non-BSP-root Makefile: {makefile}")

    drivers = [d.strip() for d in args.sequential_drivers.split(",") if d.strip()]
    sequential = " ".join(f"ps7_cortexa9_0/libsrc/{d}/src/Makefile" for d in drivers)
    content = (
        MAKEFILE_2021_1_FIX
        .replace("__SEQUENTIAL_MAKEFILES__", sequential)
        .replace("__JOBS__", str(args.jobs))
    )

    for makefile in makefiles:
        print(f"Patching {makefile}")
        if args.dry_run:
            continue
        backup = makefile.with_suffix(makefile.suffix + ".bak")
        if not backup.exists():
            shutil.copy2(makefile, backup)
        makefile.write_text(content, encoding="utf-8", newline="\n")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Vivado/Vitis automation helper")
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="Save Vivado 2020.2 and 2021.1 executable paths")
    init.add_argument("--vivado-2020-2", default="", help="Path to Vivado 2020.2 executable")
    init.add_argument("--vivado-2021-1", default="", help="Path to Vivado 2021.1 executable")
    init.add_argument(
        "--default-version",
        default="auto",
        choices=["auto", "2020.2", "2021.1"],
        help="Default Vivado for normal commands",
    )
    init.add_argument("--assistant-config", default=str(default_config_path()), help="Config JSON path")
    init.set_defaults(func=init_config_cmd)

    reg_xdc = sub.add_parser("register-board-xdc", help="Register an original board XDC path in config")
    reg_xdc.add_argument("--board-name", required=True, help="Short board key, e.g. pynq-z2")
    reg_xdc.add_argument("--xdc", required=True, help="Original board XDC file path")
    reg_xdc.add_argument("--part", default="", help="Optional default part for this board")
    reg_xdc.add_argument("--board-part", default="", help="Optional Vivado board_part, e.g. tul.com.tw:pynq-z2:part0:1.0")
    reg_xdc.add_argument("--description", default="")
    reg_xdc.add_argument("--assistant-config", default=str(default_config_path()))
    reg_xdc.set_defaults(func=register_board_xdc_cmd)

    list_xdc = sub.add_parser("list-board-xdc", help="List registered board XDC paths")
    list_xdc.add_argument("--assistant-config", default=str(default_config_path()))
    list_xdc.set_defaults(func=list_board_xdc_cmd)

    doctor = sub.add_parser("doctor", help="Validate host, config, and Vivado launcher paths")
    doctor.add_argument("--assistant-config", default=str(default_config_path()))
    doctor.add_argument(
        "--vivado-candidate",
        action="append",
        default=[],
        help="Path pasted by a user, such as bin/vivado.bat, an unwrapped/win64.o folder, or another candidate",
    )
    doctor.set_defaults(func=doctor_cmd)

    hard = sub.add_parser(
        "run-rtl-workflow",
        help="Hard ordered workflow: create project, add files, optional BD, output products, synth, impl, bitstream, XSA",
    )
    hard.add_argument("--name", required=True)
    hard.add_argument("--root", required=True, help="One clean project root owned by this workflow")
    hard.add_argument("--part", required=True)
    hard.add_argument("--board-part", default="", help="Vivado board_part, for example tul.com.tw:pynq-z2:part0:1.0")
    hard.add_argument("--top", default="")
    hard.add_argument("--src-dir", default="./src/hdl")
    hard.add_argument("--sim-dir", default="./src/tb")
    hard.add_argument("--xdc-dir", default="./src/xdc")
    hard.add_argument("--xdc", default="", help="Additional exact XDC file")
    hard.add_argument("--board-name", default="", help="Use registered board XDC from config")
    hard.add_argument("--language", default="Verilog", choices=["Verilog", "VHDL"])
    hard.add_argument("--bd-mode", default="none", choices=["none", "zynq-ps", "zynq-axi-gpio"])
    hard.add_argument("--bd-name", default="design_1")
    hard.add_argument("--ps-uart", default="none", choices=["none", "uart0", "uart1"], help="Enable and assert a PS UART for serial-print applications")
    hard.add_argument("--gpio-width", type=int, default=1)
    hard.add_argument("--gpio-direction", default="input", choices=["input", "output"])
    hard.add_argument("--gpio-port-name", default="gpio_0")
    hard.add_argument("--clock-mhz", type=int, default=100)
    hard.add_argument("--jobs", type=int, default=4)
    hard.add_argument("--synth-strategy", default="Flow_PerfOptimized_high")
    hard.add_argument("--impl-strategy", default="Performance_ExplorePostRoutePhysOpt")
    hard.add_argument("--export-hw", action="store_true", help="Write XSA after bitstream")
    hard.add_argument("--vivado-version", default="", choices=["", "2020.2", "2021.1"])
    hard.add_argument("--vivado", default="", help="Override Vivado executable")
    hard.add_argument("--assistant-config", default=str(default_config_path()))
    hard.add_argument("--automation-dir", default="", help="Optional external directory for generated Tcl/log/debug files; defaults to system temp")
    hard.add_argument("--plan-only", action="store_true", help="Generate manifest/Tcl for inspection only; do not use for normal automation")
    hard.add_argument("--run", action="store_true")
    hard.set_defaults(func=hard_rtl_workflow_cmd)

    create = sub.add_parser("create-project", help="Create a Vivado project from source folders")
    create.add_argument("--name", required=True)
    create.add_argument("--part", required=True)
    create.add_argument("--project-dir", required=True)
    create.add_argument("--src-dir", default="./src/hdl")
    create.add_argument("--sim-dir", default="./src/tb")
    create.add_argument("--xdc-dir", default="./src/xdc")
    create.add_argument("--ip-dir", default="./ip")
    create.add_argument("--bd-dir", default="./src/bd")
    create.add_argument("--board-name", default="", help="Use registered board XDC from config")
    create.add_argument("--top", default="")
    create.add_argument("--language", default="Verilog", choices=["Verilog", "VHDL"])
    create.add_argument("--out", required=True, help="Automation Tcl output directory")
    create.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    create.add_argument("--assistant-config", default=str(default_config_path()))
    create.add_argument("--run", action="store_true")
    create.set_defaults(func=create_project_cmd)

    bd = sub.add_parser("create-bd", help="Create a baseline Zynq PS + AXI GPIO block design")
    bd.add_argument("--project", required=True, help=".xpr path")
    bd.add_argument("--bd-name", default="design_1")
    bd.add_argument("--gpio-width", type=int, default=8)
    bd.add_argument("--clock-mhz", type=int, default=100)
    bd.add_argument("--out", required=True)
    bd.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    bd.add_argument("--assistant-config", default=str(default_config_path()))
    bd.add_argument("--run", action="store_true")
    bd.set_defaults(func=create_bd_cmd)

    outp = sub.add_parser("generate-output-products", help="Generate all IP/BD output products")
    outp.add_argument("--project", required=True)
    outp.add_argument("--out", required=True)
    outp.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    outp.add_argument("--assistant-config", default=str(default_config_path()))
    outp.add_argument("--run", action="store_true")
    outp.set_defaults(func=output_products_cmd)

    synth = sub.add_parser("run-synthesis", help="Run synthesis and reports")
    synth.add_argument("--project", required=True)
    synth.add_argument("--name", default="design")
    synth.add_argument("--strategy", default="Flow_PerfOptimized_high")
    synth.add_argument("--jobs", type=int, default=4)
    synth.add_argument("--reports-dir", default="./reports")
    synth.add_argument("--checkpoint-dir", default="./checkpoints")
    synth.add_argument("--bitstream-dir", default="./bitstreams")
    synth.add_argument("--out", required=True)
    synth.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    synth.add_argument("--assistant-config", default=str(default_config_path()))
    synth.add_argument("--run", action="store_true")
    synth.set_defaults(func=run_flow_cmd, step="synthesis")

    impl = sub.add_parser("run-implementation", help="Run implementation and reports")
    impl.add_argument("--project", required=True)
    impl.add_argument("--name", default="design")
    impl.add_argument("--strategy", default="Performance_ExplorePostRoutePhysOpt")
    impl.add_argument("--jobs", type=int, default=4)
    impl.add_argument("--reports-dir", default="./reports")
    impl.add_argument("--checkpoint-dir", default="./checkpoints")
    impl.add_argument("--bitstream-dir", default="./bitstreams")
    impl.add_argument("--out", required=True)
    impl.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    impl.add_argument("--assistant-config", default=str(default_config_path()))
    impl.add_argument("--run", action="store_true")
    impl.set_defaults(func=run_flow_cmd, step="implementation")

    bit = sub.add_parser("generate-bitstream", help="Run implementation to standard impl_1 bitstream")
    bit.add_argument("--project", required=True)
    bit.add_argument("--name", required=True)
    bit.add_argument("--strategy", default="Performance_ExplorePostRoutePhysOpt")
    bit.add_argument("--jobs", type=int, default=4)
    bit.add_argument("--reports-dir", default="./reports")
    bit.add_argument("--checkpoint-dir", default="./checkpoints")
    bit.add_argument("--bitstream-dir", default="./bitstreams", help=argparse.SUPPRESS)
    bit.add_argument("--out", required=True)
    bit.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    bit.add_argument("--assistant-config", default=str(default_config_path()))
    bit.add_argument("--ask-program-device", action="store_true", help="Ask after bitstream whether to open hardware and program")
    bit.add_argument("--program-device", action="store_true", help="Program device automatically after bitstream")
    bit.add_argument("--hw-server-url", default="localhost:3121")
    bit.add_argument("--device-index", type=int, default=0)
    bit.add_argument("--ltx-file", default="")
    bit.add_argument("--run", action="store_true")
    bit.set_defaults(func=run_flow_cmd, step="bitstream")

    prog = sub.add_parser("program-device", help="Open hardware and program a device with a bitstream")
    prog.add_argument("--bit-file", required=True)
    prog.add_argument("--ltx-file", default="")
    prog.add_argument("--hw-server-url", default="localhost:3121")
    prog.add_argument("--device-index", type=int, default=0)
    prog.add_argument("--out", required=True)
    prog.add_argument("--vivado", default="", help="Override Vivado executable")
    prog.add_argument("--assistant-config", default=str(default_config_path()))
    prog.add_argument("--run", action="store_true")
    prog.set_defaults(func=program_device_cmd)

    sim = sub.add_parser("run-simulation", help="Run XSim project-mode simulation")
    sim.add_argument("--project", required=True)
    sim.add_argument("--top", required=True)
    sim.add_argument("--runtime", default="10us")
    sim.add_argument("--results-dir", default="./sim_results")
    sim.add_argument("--out", required=True)
    sim.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    sim.add_argument("--assistant-config", default=str(default_config_path()))
    sim.add_argument("--run", action="store_true")
    sim.set_defaults(func=simulate_cmd)

    ip = sub.add_parser("ip", help="Create or edit Vivado catalog IP")
    ip.add_argument("--ip-action", choices=["create", "edit"], required=True)
    ip.add_argument("--project", required=True)
    ip.add_argument("--ip-name", default="")
    ip.add_argument("--module-name", required=True)
    ip.add_argument("--version", default="")
    ip.add_argument("--ip-dir", default="./ip")
    ip.add_argument("--config", nargs="*", default=[], help="Vivado CONFIG pairs, e.g. CONFIG.C_GPIO_WIDTH {8}")
    ip.add_argument("--out", required=True)
    ip.add_argument("--vivado", default="", help="Override Vivado executable; defaults to config Vivado 2021.1")
    ip.add_argument("--assistant-config", default=str(default_config_path()))
    ip.add_argument("--run", action="store_true")
    ip.set_defaults(func=ip_cmd)

    migrate = sub.add_parser("migrate-project", help="Rebuild a project across Vivado versions")
    migrate.add_argument("--project", required=True, help="Old .xpr file or project directory")
    migrate.add_argument("--out", required=True, help="Migration working directory")
    migrate.add_argument("--new-project-dir", required=True, help="Directory for the rebuilt target project")
    migrate.add_argument("--source-version", default="", choices=["2020.2", "2021.1"], help="Source Vivado version from config")
    migrate.add_argument("--target-version", default="", choices=["2020.2", "2021.1"], help="Target Vivado version from config")
    migrate.add_argument("--source-vivado", default="", help="Override source Vivado executable")
    migrate.add_argument("--target-vivado", default="", help="Override target Vivado executable")
    migrate.add_argument("--assistant-config", default=str(default_config_path()))
    migrate.add_argument("--run-export", action="store_true", help="Run source Vivado export step now")
    migrate.add_argument("--run-rebuild", action="store_true", help="Run target Vivado rebuild step now")
    migrate.set_defaults(func=migrate_project)

    patch = sub.add_parser("patch-vitis-makefile", help="Patch Vivado/Vitis 2021.1 BSP Makefile bug")
    patch.add_argument("--workspace", required=True, help="Vitis app workspace")
    patch.add_argument("--makefile", help="Specific BSP Makefile to patch")
    patch.add_argument("--jobs", type=int, default=30, help="Parallel make jobs for par_libs")
    patch.add_argument(
        "--sequential-drivers",
        default="",
        help="Comma-separated ps7_cortexa9_0/libsrc driver folder names to build sequentially (e.g. xilffs_v4_4,xilpm_v2_9)",
    )
    patch.add_argument("--dry-run", action="store_true", help="Only print matched Makefiles")
    patch.set_defaults(func=patch_vitis_makefile)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
